server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/eureka
#  instance:
#    hostname: 127.0.0.1

spring:
  jmx:
    enabled: false
    
application.resource.message : This is the First Message !